"use client";
import { useActionState } from "react";
import Link from "next/link";
import type { EditorialActionState } from "@/domain/editorial/action-state";
import { initialEditorialActionState } from "@/domain/editorial/action-state";
import { contactCategories } from "@/domain/communication/contact-model";

const field = "mt-2 w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/15";
export function ContactForm({ action }: { action: (state: EditorialActionState, formData: FormData) => Promise<EditorialActionState> }) { const [state, formAction] = useActionState(action, initialEditorialActionState); const errors = state.fieldErrors ?? {}; return <form action={formAction} className="grid gap-5 rounded-2xl border border-border bg-surface p-5 sm:p-7">{state.message ? <p role={state.status === "error" ? "alert" : "status"} className={`rounded-xl p-4 text-sm font-semibold ${state.status === "error" ? "bg-red-50 text-danger" : "bg-accent-soft text-brand"}`}>{state.message}</p> : null}<div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Nume *<input name="name" required maxLength={120} className={field} />{errors.name ? <span className="mt-1 block text-xs text-danger">{errors.name[0]}</span> : null}</label><label className="text-sm font-semibold">Email *<input name="email" type="email" required maxLength={320} className={field} />{errors.email ? <span className="mt-1 block text-xs text-danger">{errors.email[0]}</span> : null}</label><label className="text-sm font-semibold">Telefon<input name="phone" type="tel" maxLength={50} className={field} /></label><label className="text-sm font-semibold">Tip solicitare *<select name="category" required defaultValue="general" className={field}>{contactCategories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold md:col-span-2">Subiect *<input name="subject" required minLength={3} maxLength={200} className={field} />{errors.subject ? <span className="mt-1 block text-xs text-danger">{errors.subject[0]}</span> : null}</label><label className="text-sm font-semibold md:col-span-2">Mesaj *<textarea name="message" required minLength={20} maxLength={10000} rows={8} className={field} />{errors.message ? <span className="mt-1 block text-xs text-danger">{errors.message[0]}</span> : null}</label><label className="sr-only" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label></div><label className="flex items-start gap-3 text-sm"><input name="privacyAccepted" type="checkbox" required className="mt-1 size-4 accent-[var(--brand)]" /><span>Sunt de acord ca datele trimise să fie folosite pentru soluționarea solicitării, conform <Link href="/legal/confidentialitate" className="font-semibold underline">politicii de confidențialitate</Link>.</span></label>{errors.privacyAccepted ? <span className="text-xs text-danger">{errors.privacyAccepted[0]}</span> : null}<button className="min-h-12 justify-self-start rounded-full bg-brand px-6 text-sm font-semibold text-white hover:bg-brand-hover">Trimite mesajul</button></form>; }
