import type { Metadata } from "next";
import Link from "next/link";
import { AdminPageHeader, EmptyState } from "@/components/admin/editorial-ui";
import { contactCategories, contactStatuses } from "@/domain/communication/contact-model";
import { getAdminContactMessages } from "@/domain/communication/contact-service";
import { requireSectionAccess } from "@/lib/auth/principal";
export const metadata: Metadata = { title: "Mesaje" };
const label = (items: readonly (readonly [string, string])[], value: string) => items.find((item) => item[0] === value)?.[1] ?? value;
export default async function MessagesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; category?: string }> }) { await requireSectionAccess("messages"); const filters = await searchParams; const rows = await getAdminContactMessages(filters); return <><AdminPageHeader eyebrow="Comunicare" title="Mesaje" description="Inbox-ul solicitărilor publice, cu status, responsabil și istoric complet." /><form className="mb-6 grid gap-3 rounded-2xl border border-border bg-surface p-4 md:grid-cols-[minmax(0,1fr)_14rem_14rem_auto]"><input name="q" type="search" defaultValue={filters.q ?? ""} placeholder="Caută expeditor, email sau subiect…" className="rounded-xl border border-border bg-paper px-4 py-2.5 text-sm" /><select name="status" defaultValue={filters.status ?? ""} className="rounded-xl border border-border bg-paper px-3 py-2.5 text-sm"><option value="">Toate statusurile</option>{contactStatuses.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select><select name="category" defaultValue={filters.category ?? ""} className="rounded-xl border border-border bg-paper px-3 py-2.5 text-sm"><option value="">Toate tipurile</option>{contactCategories.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select><button className="min-h-11 rounded-full bg-brand px-5 text-sm font-semibold text-white">Filtrează</button></form>{rows.length ? <div className="overflow-x-auto rounded-2xl border border-border bg-surface"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-border bg-paper text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Data</th><th className="px-5 py-4">Expeditor</th><th className="px-5 py-4">Subiect</th><th className="px-5 py-4">Tip</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Responsabil</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row.id} className={row.status === "new" ? "bg-accent-soft/40" : ""}><td className="whitespace-nowrap px-5 py-4 text-muted">{new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium", timeStyle: "short" }).format(row.createdAt)}</td><td className="px-5 py-4"><span className="font-semibold">{row.name}</span><span className="mt-1 block text-xs text-muted">{row.email}</span></td><td className="px-5 py-4"><Link href={`/admin/messages/${row.id}`} className="font-semibold text-brand underline underline-offset-4">{row.subject}</Link></td><td className="px-5 py-4 text-muted">{label(contactCategories, row.category)}</td><td className="px-5 py-4"><span className="rounded-full bg-paper px-2.5 py-1 text-xs font-bold">{label(contactStatuses, row.status)}</span></td><td className="px-5 py-4 text-muted">{row.assignedName ?? "Neatribuit"}</td></tr>)}</tbody></table></div> : <EmptyState>Nu există mesaje pentru filtrele selectate.</EmptyState>}</>; }
