import { boolean, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

import { timestamps } from "./common";
import { users } from "./identity";
import { mediaAssets } from "./media";

export const siteSettings = pgTable("site_settings", {
  key: text("key").primaryKey(),
  siteName: text("site_name").default("Cartea Zilei").notNull(),
  shortName: text("short_name").default("Cartea Zilei").notNull(),
  siteTagline: text("site_tagline").default("Recomandări explicate. Mai puține titluri. Alegeri mai bune.").notNull(),
  siteDescription: text("site_description").default("Platformă editorială de recomandări de carte.").notNull(),
  primaryUrl: text("primary_url").default("https://carteazilei.ro").notNull(),
  defaultLanguage: text("default_language").default("ro").notNull(),
  timezone: text("timezone").default("Europe/Bucharest").notNull(),
  copyrightText: text("copyright_text"),
  legalOperatorName: text("legal_operator_name"),
  defaultMetaTitle: text("default_meta_title").default("Cartea Zilei — Recomandări de cărți explicate").notNull(),
  defaultMetaDescription: text("default_meta_description").default("Recomandări editoriale și personalizate care te ajută să alegi următoarea carte bună.").notNull(),
  titleTemplate: text("title_template").default("%s | Cartea Zilei").notNull(),
  canonicalHost: text("canonical_host").default("https://carteazilei.ro").notNull(),
  indexingEnabled: boolean("indexing_enabled").default(true).notNull(),
  googleSiteVerification: text("google_site_verification"),
  bingSiteVerification: text("bing_site_verification"),
  logoAssetId: uuid("logo_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  darkLogoAssetId: uuid("dark_logo_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  compactLogoAssetId: uuid("compact_logo_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  faviconAssetId: uuid("favicon_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  appleTouchIconAssetId: uuid("apple_touch_icon_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  defaultOgAssetId: uuid("default_og_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  bookPlaceholderAssetId: uuid("book_placeholder_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }),
  primaryColor: text("primary_color").default("#123f35").notNull(),
  accentColor: text("accent_color").default("#a66f19").notNull(),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  contactAddress: text("contact_address"),
  socialFacebook: text("social_facebook"),
  socialInstagram: text("social_instagram"),
  socialTiktok: text("social_tiktok"),
  socialYoutube: text("social_youtube"),
  socialLinkedin: text("social_linkedin"),
  socialX: text("social_x"),
  socialGoodreads: text("social_goodreads"),
  affiliateDisclosure: text("affiliate_disclosure"),
  companyName: text("company_name"),
  companyTaxId: text("company_tax_id"),
  companyRegistryNumber: text("company_registry_number"),
  companyFiscalAddress: text("company_fiscal_address"),
  commercialEmail: text("commercial_email"),
  partnershipDefaultText: text("partnership_default_text"),
  featureRecommendation: boolean("feature_recommendation").default(true).notNull(),
  featureDailyArchive: boolean("feature_daily_archive").default(true).notNull(),
  featureNewsletter: boolean("feature_newsletter").default(false).notNull(),
  featureContactForm: boolean("feature_contact_form").default(true).notNull(),
  featureWhatsApp: boolean("feature_whatsapp").default(false).notNull(),
  featureUserReviews: boolean("feature_user_reviews").default(false).notNull(),
  featurePublicAccounts: boolean("feature_public_accounts").default(false).notNull(),
  featurePrices: boolean("feature_prices").default(true).notNull(),
  featureOfferComparison: boolean("feature_offer_comparison").default(true).notNull(),
  maintenanceEnabled: boolean("maintenance_enabled").default(false).notNull(),
  maintenanceTitle: text("maintenance_title").default("Revenim în curând").notNull(),
  maintenanceMessage: text("maintenance_message").default("Lucrăm la îmbunătățirea site-ului.").notNull(),
  maintenanceEstimatedAt: timestamp("maintenance_estimated_at", { withTimezone: true }),
  whatsappNumber: text("whatsapp_number"),
  whatsappMessage: text("whatsapp_message").default("Bună! Am ajuns de pe CarteaZilei.ro și aș dori mai multe informații.").notNull(),
  whatsappLabel: text("whatsapp_label").default("Scrie-ne pe WhatsApp").notNull(),
  whatsappPosition: text("whatsapp_position").default("right").notNull(),
  whatsappShowDesktop: boolean("whatsapp_show_desktop").default(true).notNull(),
  whatsappShowMobile: boolean("whatsapp_show_mobile").default(true).notNull(),
  whatsappIncludedPaths: text("whatsapp_included_paths").array(),
  whatsappExcludedPaths: text("whatsapp_excluded_paths").array(),
  whatsappSchedule: jsonb("whatsapp_schedule").$type<Record<string, unknown>>(),
  whatsappOnlineMessage: text("whatsapp_online_message"),
  whatsappOfflineMessage: text("whatsapp_offline_message"),
  whatsappColor: text("whatsapp_color"),
  whatsappTrackingEnabled: boolean("whatsapp_tracking_enabled").default(true).notNull(),
  cookieBannerEnabled: boolean("cookie_banner_enabled").default(true).notNull(),
  analyticsEnabled: boolean("analytics_enabled").default(true).notNull(),
  cookieTitle: text("cookie_title").notNull(),
  cookieDescription: text("cookie_description").notNull(),
  privacyControllerName: text("privacy_controller_name").notNull(),
  privacyContactEmail: text("privacy_contact_email"),
  privacyContactAddress: text("privacy_contact_address"),
  privacyRetentionText: text("privacy_retention_text").notNull(),
  privacyAdditionalText: text("privacy_additional_text"),
  updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }),
  ...timestamps(),
});
