import "server-only";
import { and, asc, desc, eq, isNull } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { mediaAssets, staticPages, users } from "@/db/schema";
import { writeAuditLog } from "@/lib/audit/service";
import { slugify } from "@/lib/slug";
import { EditorialServiceError } from "./action-state";
import { optionalStringValue, stringValue, zodFieldErrors } from "./form-data";
const inputSchema = z.object({ title: z.string().trim().min(2).max(200), slug: z.string().trim().max(160).optional(), excerpt: z.string().trim().max(500).optional(), content: z.string().trim().min(20, "Conținutul este prea scurt.").max(100_000), status: z.enum(["draft", "published", "archived"]), metaTitle: z.string().trim().max(100).optional(), metaDescription: z.string().trim().max(200).optional(), ogImageAssetId: z.uuid().optional() });
export function parseStaticPageFormData(formData: FormData) { const parsed = inputSchema.safeParse({ title: stringValue(formData, "title"), slug: optionalStringValue(formData, "slug"), excerpt: optionalStringValue(formData, "excerpt"), content: stringValue(formData, "content"), status: stringValue(formData, "status"), metaTitle: optionalStringValue(formData, "metaTitle"), metaDescription: optionalStringValue(formData, "metaDescription"), ogImageAssetId: optionalStringValue(formData, "ogImageAssetId") }); if (!parsed.success) throw new EditorialServiceError("Corectează câmpurile paginii.", zodFieldErrors(parsed.error)); return { ...parsed.data, slug: slugify(parsed.data.slug || parsed.data.title) }; }
export async function getAdminStaticPages() { return getDb().select({ id: staticPages.id, title: staticPages.title, slug: staticPages.slug, status: staticPages.status, updatedAt: staticPages.updatedAt, authorName: users.name }).from(staticPages).leftJoin(users, eq(users.id, staticPages.authorUserId)).where(isNull(staticPages.deletedAt)).orderBy(desc(staticPages.updatedAt)); }
export async function getAdminStaticPage(id: string) { const parsed = z.uuid().safeParse(id); if (!parsed.success) return null; const db = getDb(); const [page, media] = await Promise.all([db.select().from(staticPages).where(and(eq(staticPages.id, parsed.data), isNull(staticPages.deletedAt))).limit(1), db.select({ id: mediaAssets.id, altText: mediaAssets.altText }).from(mediaAssets).where(isNull(mediaAssets.deletedAt)).orderBy(asc(mediaAssets.altText))]); return page[0] ? { page: page[0], media } : null; }
export async function getPublicStaticPage(slug: string) { return (await getDb().select({ id: staticPages.id, title: staticPages.title, excerpt: staticPages.excerpt, content: staticPages.content, metaTitle: staticPages.metaTitle, metaDescription: staticPages.metaDescription, ogImageAssetId: staticPages.ogImageAssetId, publishedAt: staticPages.publishedAt, updatedAt: staticPages.updatedAt, authorName: users.name }).from(staticPages).leftJoin(users, eq(users.id, staticPages.authorUserId)).where(and(eq(staticPages.slug, slug), eq(staticPages.status, "published"), isNull(staticPages.deletedAt))).limit(1))[0] ?? null; }
export async function saveStaticPage(input: z.infer<typeof inputSchema> & { slug: string }, actorUserId: string, id?: string) { const db = getDb(); try { return await db.transaction(async (transaction) => { if (input.ogImageAssetId) { const [asset] = await transaction.select({ id: mediaAssets.id }).from(mediaAssets).where(and(eq(mediaAssets.id, input.ogImageAssetId), isNull(mediaAssets.deletedAt))).limit(1); if (!asset) throw new EditorialServiceError("Imaginea OG nu mai este disponibilă."); } const current = id ? (await transaction.select({ status: staticPages.status }).from(staticPages).where(and(eq(staticPages.id, id), isNull(staticPages.deletedAt))).limit(1))[0] : null; const values = { ...input, excerpt: input.excerpt ?? null, metaTitle: input.metaTitle ?? null, metaDescription: input.metaDescription ?? null, ogImageAssetId: input.ogImageAssetId ?? null, authorUserId: actorUserId, publishedAt: input.status === "published" ? current?.status === "published" ? undefined : new Date() : null, updatedAt: new Date() }; const [saved] = id ? await transaction.update(staticPages).set(values).where(eq(staticPages.id, id)).returning({ id: staticPages.id }) : await transaction.insert(staticPages).values(values).returning({ id: staticPages.id }); if (!saved) throw new EditorialServiceError("Pagina nu a putut fi salvată."); await writeAuditLog({ actorUserId, action: id ? "page.edit" : "page.create", entityType: "page", entityId: saved.id, diff: { title: input.title, slug: input.slug, status: input.status } }, transaction); return saved.id; }); } catch (error) { if (error instanceof EditorialServiceError) throw error; if (typeof error === "object" && error && "code" in error && error.code === "23505") throw new EditorialServiceError("Slugul este deja folosit.", { slug: ["Alege alt slug."] }); throw error; } }
export async function deleteStaticPage(id: string, actorUserId: string) { const db = getDb(); await db.transaction(async (transaction) => { const [page] = await transaction.update(staticPages).set({ status: "archived", deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(staticPages.id, id), isNull(staticPages.deletedAt))).returning({ id: staticPages.id, title: staticPages.title }); if (!page) throw new EditorialServiceError("Pagina nu mai există."); await writeAuditLog({ actorUserId, action: "page.delete", entityType: "page", entityId: id, diff: { title: page.title } }, transaction); }); }
