INSERT INTO "genres" ("name", "slug") VALUES
  ('Acțiune și aventură', 'actiune-si-aventura'),
  ('Artă și design', 'arta-si-design'),
  ('Benzi desenate și romane grafice', 'benzi-desenate-si-romane-grafice'),
  ('Biografie', 'biografie'),
  ('Călătorii', 'calatorii'),
  ('Cărți pentru copii', 'carti-pentru-copii'),
  ('Distopie', 'distopie'),
  ('Dramaturgie', 'dramaturgie'),
  ('Economie și finanțe', 'economie-si-finante'),
  ('Eseu', 'eseu'),
  ('Ficțiune istorică', 'fictiune-istorica'),
  ('Filosofie', 'filosofie'),
  ('Gastronomie', 'gastronomie'),
  ('Horror', 'horror'),
  ('Literatură clasică', 'literatura-clasica'),
  ('Literatură contemporană', 'literatura-contemporana'),
  ('Mister', 'mister'),
  ('Non-ficțiune', 'non-fictiune'),
  ('Poezie', 'poezie'),
  ('Politică și societate', 'politica-si-societate'),
  ('Religie și spiritualitate', 'religie-si-spiritualitate'),
  ('Sănătate și wellbeing', 'sanatate-si-wellbeing'),
  ('Știință', 'stiinta'),
  ('Tehnologie', 'tehnologie'),
  ('True crime', 'true-crime'),
  ('Umor și satiră', 'umor-si-satira')
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "updated_at" = now();
