import { notFound } from "next/navigation";
import { AdminPageHeader } from "@/components/admin/editorial-ui";
import { ContactMessageActions } from "@/components/admin/contact-message-actions";
import { contactCategories, contactStatuses } from "@/domain/communication/contact-model";
import { getAdminContactMessage } from "@/domain/communication/contact-service";
import { requireSectionAccess } from "@/lib/auth/principal";
import { addMessageNoteAction, deleteMessageAction, replyMessageAction, updateMessageAction } from "../actions";
const label = (items: readonly (readonly [string, string])[], value: string) => items.find((item) => item[0] === value)?.[1] ?? value;
export default async function MessagePage({ params }: { params: Promise<{ id: string }> }) { await requireSectionAccess("messages"); const { id } = await params; const record = await getAdminContactMessage(id); if (!record) notFound(); const message = record.message; return <><AdminPageHeader eyebrow="Mesaj contact" title={message.subject} description={`${message.name} · ${message.email} · ${new Intl.DateTimeFormat("ro-RO", { dateStyle: "long", timeStyle: "short" }).format(message.createdAt)}`} /><section className="mb-6 rounded-2xl border border-border bg-surface p-5 sm:p-6"><dl className="grid gap-4 text-sm md:grid-cols-3"><div><dt className="font-semibold">Categorie</dt><dd className="mt-1 text-muted">{label(contactCategories, message.category)}</dd></div><div><dt className="font-semibold">Status</dt><dd className="mt-1 text-muted">{label(contactStatuses, message.status)}</dd></div><div><dt className="font-semibold">Telefon</dt><dd className="mt-1 text-muted">{message.phone ?? "—"}</dd></div></dl><div className="mt-6 whitespace-pre-wrap rounded-xl bg-paper p-5 leading-7">{message.message}</div></section>{record.events.length ? <section className="mb-6 rounded-2xl border border-border bg-surface p-5"><h2 className="font-display text-2xl font-semibold">Istoric</h2><ol className="mt-4 grid gap-3">{record.events.map((event) => <li key={event.id} className="rounded-xl bg-paper p-4 text-sm"><div className="flex justify-between gap-4"><span className="font-semibold">{event.type === "note" ? "Notă internă" : event.type === "reply" ? "Răspuns" : event.type === "assignment" ? "Atribuire" : "Status"} · {event.actorName ?? "Sistem"}</span><time className="text-xs text-muted">{new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium", timeStyle: "short" }).format(event.createdAt)}</time></div>{event.body ? <p className="mt-3 whitespace-pre-wrap leading-6">{event.body}</p> : null}</li>)}</ol></section> : null}<ContactMessageActions status={message.status} assignedTo={message.assignedTo} assignees={record.assignees} updateAction={updateMessageAction.bind(null, id)} noteAction={addMessageNoteAction.bind(null, id)} replyAction={replyMessageAction.bind(null, id)} deleteAction={deleteMessageAction.bind(null, id)} /></>; }
