"use client";
import { useActionState } from "react";
import { initialEditorialActionState, type EditorialActionState } from "@/domain/editorial/action-state";
import { contactStatuses } from "@/domain/communication/contact-model";
import { fieldClass, labelClass } from "./editorial-ui";
import { SubmitButton } from "./submit-button";

type Action = (state: EditorialActionState, formData: FormData) => Promise<EditorialActionState>;
function Message({ state }: { state: EditorialActionState }) { return state.message ? <p className={`mb-4 rounded-xl p-3 text-sm font-semibold ${state.status === "error" ? "bg-red-50 text-danger" : "bg-accent-soft text-brand"}`}>{state.message}</p> : null; }
export function ContactMessageActions({ status, assignedTo, assignees, updateAction, noteAction, replyAction, deleteAction }: { status: string; assignedTo: string | null; assignees: Array<{ id: string; name: string }>; updateAction: Action; noteAction: Action; replyAction: Action; deleteAction: Action }) { const [updateState, updateForm] = useActionState(updateAction, initialEditorialActionState); const [noteState, noteForm] = useActionState(noteAction, initialEditorialActionState); const [replyState, replyForm] = useActionState(replyAction, initialEditorialActionState); const [deleteState, deleteForm] = useActionState(deleteAction, initialEditorialActionState); return <div className="grid gap-6 lg:grid-cols-2"><form action={updateForm} className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-display text-2xl font-semibold">Flux și responsabil</h2><Message state={updateState} /><div className="mt-4 grid gap-4"><label className={labelClass}>Status<select name="status" defaultValue={status} className={fieldClass}>{contactStatuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className={labelClass}>Responsabil<select name="assignedTo" defaultValue={assignedTo ?? ""} className={fieldClass}><option value="">Neatribuit</option>{assignees.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><SubmitButton>Actualizează</SubmitButton></div></form><form action={noteForm} className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-display text-2xl font-semibold">Notă internă</h2><p className="mt-1 text-xs text-muted">Nota nu este trimisă expeditorului.</p><Message state={noteState} /><textarea name="body" required minLength={2} maxLength={5000} rows={5} className={fieldClass} /><div className="mt-4"><SubmitButton>Adaugă nota</SubmitButton></div></form><form action={replyForm} className="rounded-2xl border border-border bg-surface p-5 lg:col-span-2"><h2 className="font-display text-2xl font-semibold">Răspunde prin email</h2><p className="mt-1 text-xs text-muted">Răspunsul rămâne în istoric chiar dacă serviciul email nu este configurat.</p><Message state={replyState} /><textarea name="body" required minLength={2} maxLength={10000} rows={7} className={fieldClass} /><div className="mt-4"><SubmitButton>Salvează și trimite</SubmitButton></div></form><form action={deleteForm} onSubmit={(event) => { if (!window.confirm("Ștergi mesajul conform politicii de retenție?")) event.preventDefault(); }} className="rounded-2xl border border-danger/25 bg-red-50 p-5 lg:col-span-2"><h2 className="font-display text-xl font-semibold">Ștergere conform retenției</h2><Message state={deleteState} /><div className="mt-4"><SubmitButton variant="danger">Șterge mesajul</SubmitButton></div></form></div>; }
