"use client";

import { useActionState, type ReactNode } from "react";
import type { PublicSettingsActionState } from "@/app/admin/(protected)/settings/actions";
import type { PublicSiteSettings } from "@/domain/settings/settings-model";
import { FieldError, fieldClass, labelClass } from "./editorial-ui";
import { SubmitButton } from "./submit-button";
import { InlineMediaPicker } from "./inline-media-picker";

const initialState: PublicSettingsActionState = { status: "idle" };
type Media = Array<{ id: string; altText: string }>;
function Group({ title, description, children, open = false }: { title: string; description: string; children: ReactNode; open?: boolean }) { return <details open={open} className="rounded-2xl border border-border bg-surface shadow-sm"><summary className="cursor-pointer list-none p-5 sm:p-6"><h2 className="font-display text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-muted">{description}</p></summary><div className="border-t border-border p-5 sm:p-6">{children}</div></details>; }
function MediaSelect({ name, value, media, empty }: { name: string; value: string | null; media: Media; empty: string }) { return <InlineMediaPicker name={name} value={value} media={media} empty={empty} />; }
function Toggle({ name, checked, children }: { name: string; checked: boolean; children: ReactNode }) { return <label className="flex items-start gap-3 rounded-xl border border-border bg-paper p-4 text-sm font-semibold"><input name={name} type="checkbox" defaultChecked={checked} className="mt-0.5 size-4 accent-[var(--brand)]" /><span>{children}</span></label>; }
const scheduleDisplay = (value: Record<string, unknown> | null) => typeof value?.display === "string" ? value.display : "";

export function PublicSettingsForm({ action, values, media }: { action: (state: PublicSettingsActionState, formData: FormData) => Promise<PublicSettingsActionState>; values: PublicSiteSettings; media: Media }) {
  const [state, formAction] = useActionState(action, initialState); const errors = state.fieldErrors ?? {};
  return <form action={formAction} className="mt-6 grid gap-5">{state.message ? <p role={state.status === "error" ? "alert" : "status"} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${state.status === "error" ? "border-danger/30 bg-red-50 text-danger" : "border-brand/20 bg-accent-soft text-brand"}`}>{state.message}</p> : null}
    <Group open title="Identitate și contact" description="Datele globale folosite în site, emailuri și paginile publice."><div className="grid gap-5 md:grid-cols-2">
      <label className={labelClass}>Numele site-ului *<input name="siteName" required maxLength={100} defaultValue={values.siteName} className={fieldClass} /><FieldError errors={errors.siteName} /></label><label className={labelClass}>Nume scurt *<input name="shortName" required maxLength={50} defaultValue={values.shortName} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Slogan *<input name="siteTagline" required maxLength={240} defaultValue={values.siteTagline} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Descriere site *<textarea name="siteDescription" required rows={3} maxLength={500} defaultValue={values.siteDescription} className={fieldClass} /></label>
      <label className={labelClass}>URL principal *<input name="primaryUrl" type="url" required defaultValue={values.primaryUrl} className={fieldClass} /></label><label className={labelClass}>Fus orar *<input name="timezone" required defaultValue={values.timezone} className={fieldClass} /></label><label className={labelClass}>Limbă implicită<input name="defaultLanguage" required defaultValue={values.defaultLanguage} className={fieldClass} /></label><label className={labelClass}>Nume juridic operator<input name="legalOperatorName" defaultValue={values.legalOperatorName ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Copyright<input name="copyrightText" maxLength={300} defaultValue={values.copyrightText ?? ""} className={fieldClass} placeholder="© 2026 Cartea Zilei" /></label>
      <label className={labelClass}>Email public<input name="contactEmail" type="email" defaultValue={values.contactEmail ?? ""} className={fieldClass} /></label><label className={labelClass}>Telefon<input name="contactPhone" type="tel" defaultValue={values.contactPhone ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Adresă<textarea name="contactAddress" rows={3} defaultValue={values.contactAddress ?? ""} className={fieldClass} /></label>
    </div></Group>
    <Group title="Branding" description="Logo-uri, iconuri și culorile de bază. Imaginile provin din Biblioteca Media."><div className="grid gap-5 md:grid-cols-2">
      <label className={labelClass}>Logo principal<MediaSelect name="logoAssetId" value={values.logoAssetId} media={media} empty="Wordmark text" /></label><label className={labelClass}>Logo fundal închis<MediaSelect name="darkLogoAssetId" value={values.darkLogoAssetId} media={media} empty="Folosește logo-ul principal" /></label><label className={labelClass}>Logo compact<MediaSelect name="compactLogoAssetId" value={values.compactLogoAssetId} media={media} empty="Fără simbol separat" /></label><label className={labelClass}>Favicon<MediaSelect name="faviconAssetId" value={values.faviconAssetId} media={media} empty="Icon implicit Cartea Zilei" /></label><label className={labelClass}>Apple Touch Icon<MediaSelect name="appleTouchIconAssetId" value={values.appleTouchIconAssetId} media={media} empty="Folosește favicon" /></label><label className={labelClass}>Imagine Open Graph<MediaSelect name="defaultOgAssetId" value={values.defaultOgAssetId} media={media} empty="Fără imagine implicită" /></label><label className={labelClass}>Placeholder cărți<MediaSelect name="bookPlaceholderAssetId" value={values.bookPlaceholderAssetId} media={media} empty="Placeholder intern" /></label><label className={labelClass}>Culoare principală<input name="primaryColor" type="color" defaultValue={values.primaryColor} className={`${fieldClass} h-12`} /></label><label className={labelClass}>Culoare accent<input name="accentColor" type="color" defaultValue={values.accentColor} className={`${fieldClass} h-12`} /></label>
    </div></Group>
    <Group title="SEO global" description="Valori implicite, canonical host și verificări pentru motoarele de căutare."><div className="grid gap-5 md:grid-cols-2">
      <label className={`${labelClass} md:col-span-2`}>Titlu implicit *<input name="defaultMetaTitle" required maxLength={100} defaultValue={values.defaultMetaTitle} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Descriere implicită *<textarea name="defaultMetaDescription" required rows={3} maxLength={200} defaultValue={values.defaultMetaDescription} className={fieldClass} /></label><label className={labelClass}>Template titlu<input name="titleTemplate" required defaultValue={values.titleTemplate} className={fieldClass} /><span className="mt-1 block text-xs font-normal text-muted">Păstrează %s pentru titlul paginii.</span></label><label className={labelClass}>Canonical host<input name="canonicalHost" type="url" required defaultValue={values.canonicalHost} className={fieldClass} /></label><label className={labelClass}>Google Search Console<input name="googleSiteVerification" defaultValue={values.googleSiteVerification ?? ""} className={fieldClass} /></label><label className={labelClass}>Bing verification<input name="bingSiteVerification" defaultValue={values.bingSiteVerification ?? ""} className={fieldClass} /></label><div className="md:col-span-2"><Toggle name="indexingEnabled" checked={values.indexingEnabled}>Permite indexarea publică</Toggle></div>
    </div></Group>
    <Group title="Social media" description="În footer apar numai adresele completate."><div className="grid gap-5 md:grid-cols-2">{[["socialFacebook", "Facebook"], ["socialInstagram", "Instagram"], ["socialTiktok", "TikTok"], ["socialYoutube", "YouTube"], ["socialLinkedin", "LinkedIn"], ["socialX", "X"], ["socialGoodreads", "Goodreads"]].map(([name, label]) => <label key={name} className={labelClass}>{label}<input name={name} type="url" defaultValue={(values[name as keyof PublicSiteSettings] as string | null) ?? ""} className={fieldClass} /></label>)}</div></Group>
    <Group title="Date comerciale" description="Identitatea juridică și textele implicite pentru afiliere și parteneriate."><div className="grid gap-5 md:grid-cols-2"><label className={labelClass}>Companie<input name="companyName" defaultValue={values.companyName ?? ""} className={fieldClass} /></label><label className={labelClass}>CUI<input name="companyTaxId" defaultValue={values.companyTaxId ?? ""} className={fieldClass} /></label><label className={labelClass}>Registrul Comerțului<input name="companyRegistryNumber" defaultValue={values.companyRegistryNumber ?? ""} className={fieldClass} /></label><label className={labelClass}>Email comercial<input name="commercialEmail" type="email" defaultValue={values.commercialEmail ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Adresă fiscală<textarea name="companyFiscalAddress" rows={3} defaultValue={values.companyFiscalAddress ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Disclosure afiliere<textarea name="affiliateDisclosure" rows={4} defaultValue={values.affiliateDisclosure ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Text implicit parteneriate<textarea name="partnershipDefaultText" rows={4} defaultValue={values.partnershipDefaultText ?? ""} className={fieldClass} /></label></div></Group>
    <Group title="Funcționalități" description="Activează numai modulele pe care dorești să le afișezi public."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Toggle name="featureRecommendation" checked={values.featureRecommendation}>Recomandare personalizată</Toggle><Toggle name="featureDailyArchive" checked={values.featureDailyArchive}>Arhiva Cartea Zilei</Toggle><Toggle name="featureNewsletter" checked={values.featureNewsletter}>Newsletter</Toggle><Toggle name="featureContactForm" checked={values.featureContactForm}>Formular de contact</Toggle><Toggle name="featureWhatsApp" checked={values.featureWhatsApp}>Buton WhatsApp</Toggle><Toggle name="featureUserReviews" checked={values.featureUserReviews}>Recenzii utilizatori</Toggle><Toggle name="featurePublicAccounts" checked={values.featurePublicAccounts}>Conturi publice</Toggle><Toggle name="featurePrices" checked={values.featurePrices}>Afișare prețuri</Toggle><Toggle name="featureOfferComparison" checked={values.featureOfferComparison}>Comparație oferte</Toggle></div></Group>
    <Group title="WhatsApp" description="Buton global discret, cu afișare și tracking configurabile."><div className="grid gap-5 md:grid-cols-2"><label className={labelClass}>Număr internațional<input name="whatsappNumber" type="tel" placeholder="+40722123456" defaultValue={values.whatsappNumber ?? ""} className={fieldClass} /><FieldError errors={errors.whatsappNumber} /></label><label className={labelClass}>Etichetă<input name="whatsappLabel" required defaultValue={values.whatsappLabel} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Mesaj precompletat<textarea name="whatsappMessage" required rows={3} defaultValue={values.whatsappMessage} className={fieldClass} /></label><label className={labelClass}>Poziție<select name="whatsappPosition" defaultValue={values.whatsappPosition} className={fieldClass}><option value="right">Dreapta</option><option value="left">Stânga</option></select></label><label className={labelClass}>Culoare opțională<input name="whatsappColor" type="color" defaultValue={values.whatsappColor ?? "#25D366"} className={`${fieldClass} h-12`} /></label><label className={`${labelClass} md:col-span-2`}>Program disponibilitate<input name="whatsappScheduleText" defaultValue={scheduleDisplay(values.whatsappSchedule)} placeholder="Luni–Vineri, 09:00–18:00" className={fieldClass} /></label><label className={labelClass}>Mesaj online<input name="whatsappOnlineMessage" defaultValue={values.whatsappOnlineMessage ?? ""} className={fieldClass} /></label><label className={labelClass}>Mesaj offline<input name="whatsappOfflineMessage" defaultValue={values.whatsappOfflineMessage ?? ""} className={fieldClass} /></label><label className={labelClass}>Pagini incluse, una pe linie<textarea name="whatsappIncludedPaths" rows={4} defaultValue={(values.whatsappIncludedPaths ?? []).join("\n")} className={fieldClass} /></label><label className={labelClass}>Pagini excluse, una pe linie<textarea name="whatsappExcludedPaths" rows={4} defaultValue={(values.whatsappExcludedPaths ?? []).join("\n")} className={fieldClass} /></label><Toggle name="whatsappShowDesktop" checked={values.whatsappShowDesktop}>Afișare desktop</Toggle><Toggle name="whatsappShowMobile" checked={values.whatsappShowMobile}>Afișare mobil</Toggle><Toggle name="whatsappTrackingEnabled" checked={values.whatsappTrackingEnabled}>Măsoară clickurile</Toggle><div className={`flex items-center justify-center rounded-xl p-5 ${values.whatsappPosition === "left" ? "md:justify-start" : "md:justify-end"}`}><span style={{ backgroundColor: values.whatsappColor ?? "#25D366" }} className="rounded-full px-5 py-3 text-sm font-bold text-white">{values.whatsappLabel}</span></div></div></Group>
    <Group title="Mentenanță" description="Vizitatorii văd mesajul de mentenanță; administratorii își păstrează accesul."><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Toggle name="maintenanceEnabled" checked={values.maintenanceEnabled}>Activează modul mentenanță</Toggle></div><label className={labelClass}>Titlu<input name="maintenanceTitle" required defaultValue={values.maintenanceTitle} className={fieldClass} /></label><label className={labelClass}>Dată estimată<input name="maintenanceEstimatedAt" type="datetime-local" defaultValue={values.maintenanceEstimatedAt ? new Date(values.maintenanceEstimatedAt.getTime() - values.maintenanceEstimatedAt.getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Mesaj<textarea name="maintenanceMessage" required rows={4} defaultValue={values.maintenanceMessage} className={fieldClass} /></label></div></Group>
    <Group title="Cookie și confidențialitate" description="Consimțământ, operator și perioade de păstrare."><div className="grid gap-5 md:grid-cols-2"><Toggle name="cookieBannerEnabled" checked={values.cookieBannerEnabled}>Afișează centrul de consimțământ</Toggle><Toggle name="analyticsEnabled" checked={values.analyticsEnabled}>Permite statistici după consimțământ</Toggle><label className={labelClass}>Titlu cookie<input name="cookieTitle" required defaultValue={values.cookieTitle} className={fieldClass} /></label><label className={labelClass}>Operator date<input name="privacyControllerName" required defaultValue={values.privacyControllerName} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Explicație cookie<textarea name="cookieDescription" required rows={4} defaultValue={values.cookieDescription} className={fieldClass} /></label><label className={labelClass}>Email confidențialitate<input name="privacyContactEmail" type="email" defaultValue={values.privacyContactEmail ?? ""} className={fieldClass} /></label><label className={labelClass}>Adresă operator<textarea name="privacyContactAddress" rows={3} defaultValue={values.privacyContactAddress ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Perioade de păstrare<textarea name="privacyRetentionText" required rows={4} defaultValue={values.privacyRetentionText} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Informații suplimentare<textarea name="privacyAdditionalText" rows={5} defaultValue={values.privacyAdditionalText ?? ""} className={fieldClass} /></label></div></Group>
    <div className="sticky bottom-4 z-20 justify-self-start rounded-full bg-surface p-2 shadow-xl"><SubmitButton>Salvează toate setările</SubmitButton></div>
  </form>;
}
