"use client";

import Link from "next/link";
import { useActionState } from "react";
import { initialEditorialActionState, type EditorialActionState } from "@/domain/editorial/action-state";
import { FieldError, FormSection, fieldClass, labelClass } from "./editorial-ui";
import { InlineMediaPicker } from "./inline-media-picker";
import { SubmitButton } from "./submit-button";

type Values = { title: string; slug: string; excerpt: string | null; content: string; status: string; metaTitle: string | null; metaDescription: string | null; ogImageAssetId: string | null };
export function StaticPageForm({ action, values, media }: { action: (state: EditorialActionState, formData: FormData) => Promise<EditorialActionState>; values?: Values; media: Array<{ id: string; altText: string }> }) {
  const [state, formAction] = useActionState(action, initialEditorialActionState); const errors = state.fieldErrors ?? {};
  return <form action={formAction} className="grid gap-6">{state.status === "error" ? <p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-danger">{state.message}</p> : null}<FormSection title="Conținut" description="Editor sigur bazat pe text. Nu sunt acceptate scripturi sau HTML arbitrar."><div className="grid gap-5 md:grid-cols-2"><label className={labelClass}>Titlu *<input name="title" required maxLength={200} defaultValue={values?.title ?? ""} className={fieldClass} /></label><label className={labelClass}>Slug<input name="slug" maxLength={160} defaultValue={values?.slug ?? ""} placeholder="Se generează automat" className={fieldClass} /><FieldError errors={errors.slug} /></label><label className={`${labelClass} md:col-span-2`}>Introducere<textarea name="excerpt" rows={3} maxLength={500} defaultValue={values?.excerpt ?? ""} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Conținut *<textarea name="content" required minLength={20} maxLength={100000} rows={18} defaultValue={values?.content ?? ""} className={`${fieldClass} font-mono leading-7`} /><span className="mt-1 block text-xs font-normal text-muted">Folosește linii simple. Prefixul „## ” creează subtitluri, iar „- ” creează liste.</span><FieldError errors={errors.content} /></label><label className={labelClass}>Status<select name="status" defaultValue={values?.status ?? "draft"} className={fieldClass}><option value="draft">Ciornă</option><option value="published">Publicată</option><option value="archived">Arhivată</option></select></label><label className={labelClass}>Imagine OG<InlineMediaPicker name="ogImageAssetId" value={values?.ogImageAssetId} media={media} empty="Imaginea globală" /></label></div></FormSection><FormSection title="SEO" description="Dacă rămân goale, sunt folosite titlul și introducerea paginii."><div className="grid gap-5"><label className={labelClass}>Meta title<input name="metaTitle" maxLength={100} defaultValue={values?.metaTitle ?? ""} className={fieldClass} /></label><label className={labelClass}>Meta description<textarea name="metaDescription" rows={3} maxLength={200} defaultValue={values?.metaDescription ?? ""} className={fieldClass} /></label></div></FormSection><div className="flex gap-4"><SubmitButton>Salvează pagina</SubmitButton><Link href="/admin/pages" className="self-center text-sm font-semibold text-muted">Renunță</Link></div></form>;
}
