import "server-only";
import { and, asc, eq, isNull } from "drizzle-orm";
import { cache } from "react";
import { z } from "zod";
import { getDb } from "@/db";
import { navigationItems } from "@/db/schema";
import { EditorialServiceError } from "@/domain/editorial/action-state";
import { optionalStringValue, stringValue, zodFieldErrors } from "@/domain/editorial/form-data";
import { writeAuditLog } from "@/lib/audit/service";

const navigationInputSchema = z.object({ area: z.enum(["header", "footer"]), groupLabel: z.string().trim().max(100).optional(), label: z.string().trim().min(1).max(100), href: z.string().trim().min(1).max(500), sortOrder: z.coerce.number().int().min(0).max(10_000), active: z.boolean(), openInNewTab: z.boolean() }).superRefine((value, context) => { const internal = value.href.startsWith("/") && !value.href.startsWith("//"); let external = false; try { const url = new URL(value.href); external = url.protocol === "http:" || url.protocol === "https:"; } catch {} if (!internal && !external) context.addIssue({ code: "custom", path: ["href"], message: "Folosește o rută internă /… sau un URL https://…" }); });
export function parseNavigationFormData(formData: FormData) { const parsed = navigationInputSchema.safeParse({ area: stringValue(formData, "area"), groupLabel: optionalStringValue(formData, "groupLabel"), label: stringValue(formData, "label"), href: stringValue(formData, "href"), sortOrder: stringValue(formData, "sortOrder"), active: formData.has("active"), openInNewTab: formData.has("openInNewTab") }); if (!parsed.success) throw new EditorialServiceError("Corectează câmpurile linkului.", zodFieldErrors(parsed.error)); return parsed.data; }
export const getPublicNavigation = cache(async () => { if (process.env.NEXT_PHASE === "phase-production-build") return { header: [], footer: [] }; const rows = await getDb().select().from(navigationItems).where(and(eq(navigationItems.active, true), isNull(navigationItems.deletedAt))).orderBy(asc(navigationItems.area), asc(navigationItems.sortOrder), asc(navigationItems.label)); return { header: rows.filter((row) => row.area === "header"), footer: rows.filter((row) => row.area === "footer") }; });
export async function getAdminNavigation() { return getDb().select().from(navigationItems).where(isNull(navigationItems.deletedAt)).orderBy(asc(navigationItems.area), asc(navigationItems.sortOrder)); }
export async function getAdminNavigationItem(id: string) { const parsed = z.uuid().safeParse(id); if (!parsed.success) return null; return (await getDb().select().from(navigationItems).where(and(eq(navigationItems.id, parsed.data), isNull(navigationItems.deletedAt))).limit(1))[0] ?? null; }
export async function saveNavigationItem(input: z.infer<typeof navigationInputSchema>, actorUserId: string, id?: string) { const external = !input.href.startsWith("/"); const db = getDb(); return db.transaction(async (transaction) => { const values = { ...input, groupLabel: input.groupLabel ?? null, external, updatedAt: new Date() }; const [saved] = id ? await transaction.update(navigationItems).set(values).where(and(eq(navigationItems.id, id), isNull(navigationItems.deletedAt))).returning({ id: navigationItems.id }) : await transaction.insert(navigationItems).values(values).returning({ id: navigationItems.id }); if (!saved) throw new EditorialServiceError("Linkul nu a putut fi salvat."); await writeAuditLog({ actorUserId, action: id ? "navigation.edit" : "navigation.create", entityType: "navigation_item", entityId: saved.id, diff: values }, transaction); return saved.id; }); }
export async function deleteNavigationItem(id: string, actorUserId: string) { const db = getDb(); await db.transaction(async (transaction) => { const [saved] = await transaction.update(navigationItems).set({ active: false, deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(navigationItems.id, id), isNull(navigationItems.deletedAt))).returning({ id: navigationItems.id }); if (!saved) throw new EditorialServiceError("Linkul nu mai există."); await writeAuditLog({ actorUserId, action: "navigation.delete", entityType: "navigation_item", entityId: id }, transaction); }); }
