import "server-only";

import { and, eq, inArray, isNull } from "drizzle-orm";
import { cache } from "react";
import { z } from "zod";
import { getDb } from "@/db";
import { mediaAssets, siteSettings } from "@/db/schema";
import { EditorialServiceError } from "@/domain/editorial/action-state";
import { linesValue, optionalStringValue, stringValue, zodFieldErrors } from "@/domain/editorial/form-data";
import { writeAuditLog } from "@/lib/audit/service";
import { getServerEnv } from "@/lib/env/server";
import type { PublicSiteSettings } from "./settings-model";

export type { PublicSiteSettings } from "./settings-model";
export const publicSettingsKey = "public";
const optionalUrl = z.string().trim().url("Introdu un URL complet și valid.").max(500).optional();
const optionalEmail = z.string().trim().email("Introdu un email valid.").max(320).optional();
const optionalColor = z.string().trim().regex(/^#[0-9a-f]{6}$/i, "Folosește formatul #123ABC.").optional();

function defaultPublicSiteSettings(): PublicSiteSettings { const env = getServerEnv(); return {
  siteName: "Cartea Zilei", shortName: "Cartea Zilei", siteTagline: "Recomandări explicate. Mai puține titluri. Alegeri mai bune.", siteDescription: "Platformă editorială de recomandări de carte.", primaryUrl: env.NEXT_PUBLIC_SITE_URL, defaultLanguage: "ro", timezone: "Europe/Bucharest", copyrightText: null, legalOperatorName: null,
  defaultMetaTitle: "Cartea Zilei — Recomandări de cărți explicate", defaultMetaDescription: "Recomandări editoriale și personalizate care te ajută să alegi următoarea carte bună.", titleTemplate: "%s | Cartea Zilei", canonicalHost: env.NEXT_PUBLIC_SITE_URL, indexingEnabled: true, googleSiteVerification: null, bingSiteVerification: null,
  logoAssetId: null, darkLogoAssetId: null, compactLogoAssetId: null, faviconAssetId: null, appleTouchIconAssetId: null, defaultOgAssetId: null, bookPlaceholderAssetId: null, primaryColor: "#123f35", accentColor: "#a66f19",
  contactEmail: env.PUBLIC_CONTACT_EMAIL ?? null, contactPhone: null, contactAddress: null,
  socialFacebook: null, socialInstagram: null, socialTiktok: null, socialYoutube: null, socialLinkedin: null, socialX: null, socialGoodreads: null,
  affiliateDisclosure: null, companyName: null, companyTaxId: null, companyRegistryNumber: null, companyFiscalAddress: null, commercialEmail: null, partnershipDefaultText: null,
  featureRecommendation: true, featureDailyArchive: true, featureNewsletter: false, featureContactForm: true, featureWhatsApp: false, featureUserReviews: false, featurePublicAccounts: false, featurePrices: true, featureOfferComparison: true,
  maintenanceEnabled: false, maintenanceTitle: "Revenim în curând", maintenanceMessage: "Lucrăm la îmbunătățirea site-ului.", maintenanceEstimatedAt: null,
  whatsappNumber: null, whatsappMessage: "Bună! Am ajuns de pe CarteaZilei.ro și aș dori mai multe informații.", whatsappLabel: "Scrie-ne pe WhatsApp", whatsappPosition: "right", whatsappShowDesktop: true, whatsappShowMobile: true, whatsappIncludedPaths: [], whatsappExcludedPaths: [], whatsappSchedule: null, whatsappOnlineMessage: null, whatsappOfflineMessage: null, whatsappColor: null, whatsappTrackingEnabled: true,
  cookieBannerEnabled: true, analyticsEnabled: true, cookieTitle: "Cookie-uri și confidențialitate", cookieDescription: "Folosim cookie-uri necesare pentru funcționarea site-ului. Cu acordul tău, folosim și statistici pentru a înțelege ce pagini sunt utile.", privacyControllerName: "Cartea Zilei", privacyContactEmail: env.PUBLIC_CONTACT_EMAIL ?? null, privacyContactAddress: null, privacyRetentionText: "Identificatorul folosit pentru statisticile opționale expiră după cel mult 30 de zile. Datele sunt păstrate numai cât este necesar scopului declarat.", privacyAdditionalText: null,
}; }

const settingsInputSchema = z.object({
  siteName: z.string().trim().min(2).max(100), shortName: z.string().trim().min(2).max(50), siteTagline: z.string().trim().min(3).max(240), siteDescription: z.string().trim().min(10).max(500), primaryUrl: z.url(), defaultLanguage: z.string().trim().min(2).max(10), timezone: z.string().trim().min(3).max(100), copyrightText: z.string().trim().max(300).optional(), legalOperatorName: z.string().trim().max(200).optional(),
  defaultMetaTitle: z.string().trim().min(10).max(100), defaultMetaDescription: z.string().trim().min(30).max(200), titleTemplate: z.string().trim().min(3).max(100), canonicalHost: z.url(), indexingEnabled: z.boolean(), googleSiteVerification: z.string().trim().max(300).optional(), bingSiteVerification: z.string().trim().max(300).optional(),
  logoAssetId: z.uuid().optional(), darkLogoAssetId: z.uuid().optional(), compactLogoAssetId: z.uuid().optional(), faviconAssetId: z.uuid().optional(), appleTouchIconAssetId: z.uuid().optional(), defaultOgAssetId: z.uuid().optional(), bookPlaceholderAssetId: z.uuid().optional(), primaryColor: z.string().regex(/^#[0-9a-f]{6}$/i), accentColor: z.string().regex(/^#[0-9a-f]{6}$/i),
  contactEmail: optionalEmail, contactPhone: z.string().trim().max(50).optional(), contactAddress: z.string().trim().max(500).optional(),
  socialFacebook: optionalUrl, socialInstagram: optionalUrl, socialTiktok: optionalUrl, socialYoutube: optionalUrl, socialLinkedin: optionalUrl, socialX: optionalUrl, socialGoodreads: optionalUrl,
  affiliateDisclosure: z.string().trim().max(2_000).optional(), companyName: z.string().trim().max(200).optional(), companyTaxId: z.string().trim().max(50).optional(), companyRegistryNumber: z.string().trim().max(100).optional(), companyFiscalAddress: z.string().trim().max(500).optional(), commercialEmail: optionalEmail, partnershipDefaultText: z.string().trim().max(2_000).optional(),
  featureRecommendation: z.boolean(), featureDailyArchive: z.boolean(), featureNewsletter: z.boolean(), featureContactForm: z.boolean(), featureWhatsApp: z.boolean(), featureUserReviews: z.boolean(), featurePublicAccounts: z.boolean(), featurePrices: z.boolean(), featureOfferComparison: z.boolean(),
  maintenanceEnabled: z.boolean(), maintenanceTitle: z.string().trim().min(3).max(120), maintenanceMessage: z.string().trim().min(10).max(2_000), maintenanceEstimatedAt: z.coerce.date().optional(),
  whatsappNumber: z.string().trim().regex(/^\+[1-9]\d{7,14}$/, "Folosește format internațional, de exemplu +40722123456.").optional(), whatsappMessage: z.string().trim().min(3).max(500), whatsappLabel: z.string().trim().min(2).max(100), whatsappPosition: z.enum(["left", "right"]), whatsappShowDesktop: z.boolean(), whatsappShowMobile: z.boolean(), whatsappIncludedPaths: z.array(z.string().max(200)).max(100), whatsappExcludedPaths: z.array(z.string().max(200)).max(100), whatsappScheduleText: z.string().trim().max(500).optional(), whatsappOnlineMessage: z.string().trim().max(200).optional(), whatsappOfflineMessage: z.string().trim().max(200).optional(), whatsappColor: optionalColor, whatsappTrackingEnabled: z.boolean(),
  cookieBannerEnabled: z.boolean(), analyticsEnabled: z.boolean(), cookieTitle: z.string().trim().min(3).max(120), cookieDescription: z.string().trim().min(20).max(800), privacyControllerName: z.string().trim().min(2).max(200), privacyContactEmail: optionalEmail, privacyContactAddress: z.string().trim().max(500).optional(), privacyRetentionText: z.string().trim().min(20).max(2_000), privacyAdditionalText: z.string().trim().max(5_000).optional(),
}).superRefine((value, context) => { if (value.featureWhatsApp && !value.whatsappNumber) context.addIssue({ code: "custom", path: ["whatsappNumber"], message: "Numărul este obligatoriu când butonul este activ." }); });

export type PublicSettingsInput = z.infer<typeof settingsInputSchema>;
export function parsePublicSettingsFormData(formData: FormData): PublicSettingsInput { const optional = (name: string) => optionalStringValue(formData, name); const parsed = settingsInputSchema.safeParse({
  siteName: stringValue(formData, "siteName"), shortName: stringValue(formData, "shortName"), siteTagline: stringValue(formData, "siteTagline"), siteDescription: stringValue(formData, "siteDescription"), primaryUrl: stringValue(formData, "primaryUrl"), defaultLanguage: stringValue(formData, "defaultLanguage"), timezone: stringValue(formData, "timezone"), copyrightText: optional("copyrightText"), legalOperatorName: optional("legalOperatorName"),
  defaultMetaTitle: stringValue(formData, "defaultMetaTitle"), defaultMetaDescription: stringValue(formData, "defaultMetaDescription"), titleTemplate: stringValue(formData, "titleTemplate"), canonicalHost: stringValue(formData, "canonicalHost"), indexingEnabled: formData.has("indexingEnabled"), googleSiteVerification: optional("googleSiteVerification"), bingSiteVerification: optional("bingSiteVerification"),
  logoAssetId: optional("logoAssetId"), darkLogoAssetId: optional("darkLogoAssetId"), compactLogoAssetId: optional("compactLogoAssetId"), faviconAssetId: optional("faviconAssetId"), appleTouchIconAssetId: optional("appleTouchIconAssetId"), defaultOgAssetId: optional("defaultOgAssetId"), bookPlaceholderAssetId: optional("bookPlaceholderAssetId"), primaryColor: stringValue(formData, "primaryColor"), accentColor: stringValue(formData, "accentColor"),
  contactEmail: optional("contactEmail"), contactPhone: optional("contactPhone"), contactAddress: optional("contactAddress"), socialFacebook: optional("socialFacebook"), socialInstagram: optional("socialInstagram"), socialTiktok: optional("socialTiktok"), socialYoutube: optional("socialYoutube"), socialLinkedin: optional("socialLinkedin"), socialX: optional("socialX"), socialGoodreads: optional("socialGoodreads"),
  affiliateDisclosure: optional("affiliateDisclosure"), companyName: optional("companyName"), companyTaxId: optional("companyTaxId"), companyRegistryNumber: optional("companyRegistryNumber"), companyFiscalAddress: optional("companyFiscalAddress"), commercialEmail: optional("commercialEmail"), partnershipDefaultText: optional("partnershipDefaultText"),
  featureRecommendation: formData.has("featureRecommendation"), featureDailyArchive: formData.has("featureDailyArchive"), featureNewsletter: formData.has("featureNewsletter"), featureContactForm: formData.has("featureContactForm"), featureWhatsApp: formData.has("featureWhatsApp"), featureUserReviews: formData.has("featureUserReviews"), featurePublicAccounts: formData.has("featurePublicAccounts"), featurePrices: formData.has("featurePrices"), featureOfferComparison: formData.has("featureOfferComparison"),
  maintenanceEnabled: formData.has("maintenanceEnabled"), maintenanceTitle: stringValue(formData, "maintenanceTitle"), maintenanceMessage: stringValue(formData, "maintenanceMessage"), maintenanceEstimatedAt: optional("maintenanceEstimatedAt"),
  whatsappNumber: optional("whatsappNumber")?.replace(/[\s()-]/g, ""), whatsappMessage: stringValue(formData, "whatsappMessage"), whatsappLabel: stringValue(formData, "whatsappLabel"), whatsappPosition: stringValue(formData, "whatsappPosition"), whatsappShowDesktop: formData.has("whatsappShowDesktop"), whatsappShowMobile: formData.has("whatsappShowMobile"), whatsappIncludedPaths: linesValue(formData, "whatsappIncludedPaths"), whatsappExcludedPaths: linesValue(formData, "whatsappExcludedPaths"), whatsappScheduleText: optional("whatsappScheduleText"), whatsappOnlineMessage: optional("whatsappOnlineMessage"), whatsappOfflineMessage: optional("whatsappOfflineMessage"), whatsappColor: optional("whatsappColor"), whatsappTrackingEnabled: formData.has("whatsappTrackingEnabled"),
  cookieBannerEnabled: formData.has("cookieBannerEnabled"), analyticsEnabled: formData.has("analyticsEnabled"), cookieTitle: stringValue(formData, "cookieTitle"), cookieDescription: stringValue(formData, "cookieDescription"), privacyControllerName: stringValue(formData, "privacyControllerName"), privacyContactEmail: optional("privacyContactEmail"), privacyContactAddress: optional("privacyContactAddress"), privacyRetentionText: stringValue(formData, "privacyRetentionText"), privacyAdditionalText: optional("privacyAdditionalText"),
 }); if (!parsed.success) throw new EditorialServiceError("Corectează câmpurile marcate.", zodFieldErrors(parsed.error)); return parsed.data; }

export const getPublicSiteSettings = cache(async (): Promise<PublicSiteSettings> => { if (process.env.NEXT_PHASE === "phase-production-build") return defaultPublicSiteSettings(); const [record] = await getDb().select().from(siteSettings).where(eq(siteSettings.key, publicSettingsKey)).limit(1); return record ?? defaultPublicSiteSettings(); });

export async function savePublicSiteSettings(input: PublicSettingsInput, actorUserId: string) { const db = getDb(); await db.transaction(async (transaction) => { const assetIds = [input.logoAssetId, input.darkLogoAssetId, input.compactLogoAssetId, input.faviconAssetId, input.appleTouchIconAssetId, input.defaultOgAssetId, input.bookPlaceholderAssetId].filter((id): id is string => Boolean(id)); if (assetIds.length) { const available = await transaction.select({ id: mediaAssets.id }).from(mediaAssets).where(and(inArray(mediaAssets.id, assetIds), isNull(mediaAssets.deletedAt))); if (available.length !== new Set(assetIds).size) throw new EditorialServiceError("Una dintre imaginile selectate nu mai este disponibilă."); }
  const { whatsappScheduleText, ...plainInput } = input; const nullableKeys = ["copyrightText", "legalOperatorName", "googleSiteVerification", "bingSiteVerification", "logoAssetId", "darkLogoAssetId", "compactLogoAssetId", "faviconAssetId", "appleTouchIconAssetId", "defaultOgAssetId", "bookPlaceholderAssetId", "contactEmail", "contactPhone", "contactAddress", "socialFacebook", "socialInstagram", "socialTiktok", "socialYoutube", "socialLinkedin", "socialX", "socialGoodreads", "affiliateDisclosure", "companyName", "companyTaxId", "companyRegistryNumber", "companyFiscalAddress", "commercialEmail", "partnershipDefaultText", "maintenanceEstimatedAt", "whatsappNumber", "whatsappOnlineMessage", "whatsappOfflineMessage", "whatsappColor", "privacyContactEmail", "privacyContactAddress", "privacyAdditionalText"] as const; const values: Record<string, unknown> = { ...plainInput, whatsappSchedule: whatsappScheduleText ? { display: whatsappScheduleText } : null, updatedBy: actorUserId, updatedAt: new Date() }; for (const key of nullableKeys) values[key] = input[key] ?? null;
  await transaction.insert(siteSettings).values({ key: publicSettingsKey, ...(values as Omit<typeof siteSettings.$inferInsert, "key">) }).onConflictDoUpdate({ target: siteSettings.key, set: values }); await writeAuditLog({ actorUserId, action: "site_settings.edit", entityType: "site_settings", diff: { siteName: input.siteName, primaryUrl: input.primaryUrl, indexingEnabled: input.indexingEnabled, featureWhatsApp: input.featureWhatsApp, featureContactForm: input.featureContactForm, maintenanceEnabled: input.maintenanceEnabled } }, transaction); }); }
