import "server-only";

import { createHmac } from "node:crypto";
import { and, asc, desc, eq, ilike, isNull, or, sql } from "drizzle-orm";
import { z } from "zod";

import { getDb } from "@/db";
import { contactMessageEvents, contactMessages, contactRateLimits, users } from "@/db/schema";
import { EditorialServiceError } from "@/domain/editorial/action-state";
import { optionalStringValue, stringValue, zodFieldErrors } from "@/domain/editorial/form-data";
import { getPublicSiteSettings } from "@/domain/settings/public-settings-service";
import { writeAuditLog } from "@/lib/audit/service";
import { getServerEnv } from "@/lib/env/server";
import { sendBrandedEmail } from "./mail-service";
import { contactCategories, contactStatuses } from "./contact-model";

const contactInputSchema = z.object({ name: z.string().trim().min(2, "Completează numele.").max(120), email: z.email("Introdu un email valid.").max(320).transform((value) => value.trim().toLowerCase()), phone: z.string().trim().max(50).optional(), subject: z.string().trim().min(3, "Completează subiectul.").max(200), category: z.enum(contactCategories.map((item) => item[0]) as [typeof contactCategories[number][0], ...Array<typeof contactCategories[number][0]>]), message: z.string().trim().min(20, "Mesajul trebuie să aibă cel puțin 20 de caractere.").max(10_000), privacyAccepted: z.literal(true), website: z.string().max(0).optional() });

export function parseContactFormData(formData: FormData) { const parsed = contactInputSchema.safeParse({ name: stringValue(formData, "name"), email: stringValue(formData, "email"), phone: optionalStringValue(formData, "phone"), subject: stringValue(formData, "subject"), category: stringValue(formData, "category"), message: stringValue(formData, "message"), privacyAccepted: formData.has("privacyAccepted"), website: optionalStringValue(formData, "website") }); if (!parsed.success) throw new EditorialServiceError("Corectează câmpurile marcate.", zodFieldErrors(parsed.error)); return parsed.data; }

function requestHash(ip: string | null, email: string) { return createHmac("sha256", getServerEnv().AUTH_SECRET).update(`contact:${ip ?? "unknown"}:${email}`).digest("hex"); }
export function privacySafeIpHash(ip: string | null) { return ip ? createHmac("sha256", getServerEnv().AUTH_SECRET).update(`audit-ip:${ip}`).digest("hex") : null; }

async function consumeContactLimit(keyHash: string) { const db = getDb(); const now = new Date(); return db.transaction(async (transaction) => { await transaction.insert(contactRateLimits).values({ keyHash, attempts: 0, windowStartedAt: now, updatedAt: now }).onConflictDoNothing(); const [current] = await transaction.select().from(contactRateLimits).where(eq(contactRateLimits.keyHash, keyHash)).for("update").limit(1); if (!current) return false; if (current.blockedUntil && current.blockedUntil > now) return true; const expired = now.getTime() - current.windowStartedAt.getTime() > 60 * 60 * 1_000; const attempts = expired ? 1 : current.attempts + 1; const blockedUntil = attempts > 5 ? new Date(now.getTime() + 60 * 60 * 1_000) : null; await transaction.update(contactRateLimits).set({ attempts, windowStartedAt: expired ? now : current.windowStartedAt, blockedUntil, updatedAt: now }).where(eq(contactRateLimits.keyHash, keyHash)); return Boolean(blockedUntil); }); }

export async function submitContactMessage(input: z.infer<typeof contactInputSchema>, request: { ip: string | null; userAgent: string | null }) {
  if (input.website) return null;
  if (await consumeContactLimit(requestHash(request.ip, input.email))) throw new EditorialServiceError("Ai trimis prea multe mesaje. Încearcă din nou mai târziu.");
  const db = getDb();
  const [saved] = await db.insert(contactMessages).values({ name: input.name, email: input.email, phone: input.phone ?? null, subject: input.subject, category: input.category, message: input.message, privacyAcceptedAt: new Date(), ipHash: privacySafeIpHash(request.ip), userAgent: request.userAgent?.slice(0, 500) ?? null }).returning({ id: contactMessages.id });
  if (!saved) throw new EditorialServiceError("Mesajul nu a putut fi salvat.");
  await writeAuditLog({ actorUserId: null, action: "contact_message.create", entityType: "contact_message", entityId: saved.id, ipHash: privacySafeIpHash(request.ip), userAgent: request.userAgent, diff: { category: input.category, subject: input.subject } });
  const settings = await getPublicSiteSettings();
  const logoUrl = settings.logoAssetId ? `${settings.primaryUrl}/media/${settings.logoAssetId}` : null;
  if (settings.contactEmail) await sendBrandedEmail({ to: settings.contactEmail, subject: `[Contact] ${input.subject}`, siteName: settings.siteName, logoUrl, contactEmail: settings.contactEmail, bodyText: `${input.name} (${input.email}) a trimis un mesaj din categoria ${input.category}.\n\n${input.message}` }).catch((error) => console.error("Contact notification email failed", error));
  await sendBrandedEmail({ to: input.email, subject: `Am primit mesajul tău — ${settings.siteName}`, siteName: settings.siteName, logoUrl, contactEmail: settings.contactEmail, bodyText: `Bună, ${input.name}!\n\nAm primit mesajul „${input.subject}”. Echipa îl va analiza și va răspunde folosind datele transmise.\n\nNu răspunde la acest mesaj automat dacă nu este necesar.` }).catch((error) => console.error("Contact confirmation email failed", error));
  return saved.id;
}

export async function getUnreadContactCount() { const [row] = await getDb().select({ total: sql<number>`count(*)::int` }).from(contactMessages).where(and(eq(contactMessages.status, "new"), isNull(contactMessages.deletedAt))); return row?.total ?? 0; }

export async function getAdminContactMessages(filters: { q?: string; status?: string; category?: string }) { const conditions = [isNull(contactMessages.deletedAt)]; if (filters.status) conditions.push(eq(contactMessages.status, filters.status)); if (filters.category) conditions.push(eq(contactMessages.category, filters.category)); if (filters.q) conditions.push(or(ilike(contactMessages.name, `%${filters.q}%`), ilike(contactMessages.email, `%${filters.q}%`), ilike(contactMessages.subject, `%${filters.q}%`))!); return getDb().select({ id: contactMessages.id, name: contactMessages.name, email: contactMessages.email, subject: contactMessages.subject, category: contactMessages.category, status: contactMessages.status, createdAt: contactMessages.createdAt, assignedName: users.name }).from(contactMessages).leftJoin(users, eq(users.id, contactMessages.assignedTo)).where(and(...conditions)).orderBy(desc(contactMessages.createdAt)).limit(200); }

export async function getAdminContactMessage(id: string) { const parsed = z.uuid().safeParse(id); if (!parsed.success) return null; const db = getDb(); const [message, events, assignees] = await Promise.all([db.select({ message: contactMessages, assignedName: users.name }).from(contactMessages).leftJoin(users, eq(users.id, contactMessages.assignedTo)).where(and(eq(contactMessages.id, parsed.data), isNull(contactMessages.deletedAt))).limit(1), db.select({ id: contactMessageEvents.id, type: contactMessageEvents.type, body: contactMessageEvents.body, metadata: contactMessageEvents.metadata, createdAt: contactMessageEvents.createdAt, actorName: users.name }).from(contactMessageEvents).leftJoin(users, eq(users.id, contactMessageEvents.actorUserId)).where(eq(contactMessageEvents.messageId, parsed.data)).orderBy(asc(contactMessageEvents.createdAt)), db.select({ id: users.id, name: users.name }).from(users).where(and(eq(users.active, true), isNull(users.deletedAt))).orderBy(asc(users.name))]); return message[0] ? { ...message[0], events, assignees } : null; }

export async function updateContactMessage(id: string, input: { status: string; assignedTo?: string }, actorUserId: string) { const status = z.enum(contactStatuses.map((item) => item[0]) as [typeof contactStatuses[number][0], ...Array<typeof contactStatuses[number][0]>]).safeParse(input.status); const assignedTo = input.assignedTo ? z.uuid().safeParse(input.assignedTo) : null; if (!status.success || (assignedTo && !assignedTo.success)) throw new EditorialServiceError("Statusul sau responsabilul nu este valid."); const db = getDb(); await db.transaction(async (transaction) => { const [current] = await transaction.select({ status: contactMessages.status, assignedTo: contactMessages.assignedTo }).from(contactMessages).where(and(eq(contactMessages.id, id), isNull(contactMessages.deletedAt))).limit(1); if (!current) throw new EditorialServiceError("Mesajul nu mai există."); const assignment = assignedTo?.data ?? null; await transaction.update(contactMessages).set({ status: status.data, assignedTo: assignment, lastReadAt: status.data === "new" ? null : new Date(), resolvedAt: status.data === "resolved" ? new Date() : null, updatedAt: new Date() }).where(eq(contactMessages.id, id)); if (current.status !== status.data) await transaction.insert(contactMessageEvents).values({ messageId: id, actorUserId, type: "status", metadata: { from: current.status, to: status.data } }); if (current.assignedTo !== assignment) await transaction.insert(contactMessageEvents).values({ messageId: id, actorUserId, type: "assignment", metadata: { assignedTo: assignment } }); await writeAuditLog({ actorUserId, action: "contact_message.update", entityType: "contact_message", entityId: id, diff: { status: status.data, assignedTo: assignment } }, transaction); }); }

export async function addContactNote(id: string, body: string, actorUserId: string) { const parsed = z.string().trim().min(2).max(5_000).safeParse(body); if (!parsed.success) throw new EditorialServiceError("Nota internă este prea scurtă sau prea lungă."); await getDb().insert(contactMessageEvents).values({ messageId: id, actorUserId, type: "note", body: parsed.data }); await writeAuditLog({ actorUserId, action: "contact_message.note", entityType: "contact_message", entityId: id }); }

export async function replyToContactMessage(id: string, body: string, actorUserId: string) { const parsed = z.string().trim().min(2).max(10_000).safeParse(body); if (!parsed.success) throw new EditorialServiceError("Răspunsul este prea scurt sau prea lung."); const db = getDb(); const [message] = await db.select({ email: contactMessages.email, subject: contactMessages.subject, name: contactMessages.name }).from(contactMessages).where(and(eq(contactMessages.id, id), isNull(contactMessages.deletedAt))).limit(1); if (!message) throw new EditorialServiceError("Mesajul nu mai există."); const settings = await getPublicSiteSettings(); let sent = false; try { sent = await sendBrandedEmail({ to: message.email, subject: `Re: ${message.subject}`, siteName: settings.siteName, logoUrl: settings.logoAssetId ? `${settings.primaryUrl}/media/${settings.logoAssetId}` : null, contactEmail: settings.contactEmail, bodyText: parsed.data }); } catch (error) { console.error("Contact reply email failed", error); } await db.transaction(async (transaction) => { await transaction.insert(contactMessageEvents).values({ messageId: id, actorUserId, type: "reply", body: parsed.data, metadata: { sent } }); await transaction.update(contactMessages).set({ status: sent ? "waiting" : "in_progress", updatedAt: new Date() }).where(eq(contactMessages.id, id)); await writeAuditLog({ actorUserId, action: "contact_message.reply", entityType: "contact_message", entityId: id, diff: { sent } }, transaction); }); if (!sent) throw new EditorialServiceError("Răspunsul a fost salvat, dar emailul nu este configurat sau nu a putut fi trimis."); }

export async function deleteContactMessage(id: string, actorUserId: string) { const db = getDb(); await db.transaction(async (transaction) => { const [message] = await transaction.update(contactMessages).set({ status: "archived", deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(contactMessages.id, id), isNull(contactMessages.deletedAt))).returning({ id: contactMessages.id }); if (!message) throw new EditorialServiceError("Mesajul nu mai există."); await writeAuditLog({ actorUserId, action: "contact_message.delete", entityType: "contact_message", entityId: id }, transaction); }); }
